name: Auto Sync M3U8 Files

on:
  schedule:
    - cron: '*/5 * * * *'  # toutes les 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-m3u8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run TF1 Backup M3U8 update script
        run: python3 ./scripts/tf1_m3u8.py
        
      - name: Run France 2 update script
        run: python3 ./scripts/france2_m3u8.py

      - name: Run France 2 Backup update script
        run: python3 ./scripts/france2-bck_m3u8.py
        
      - name: Run France 3 update script
        run: python3 ./scripts/france3_m3u8.py

      - name: Run France 3 Backup update script
        run: python3 ./scripts/france3-bck_m3u8.py
        
      - name: Run France 4 update script
        run: python3 ./scripts/france4_m3u8.py

      - name: Run France 5 update script
        run: python3 ./scripts/france5_m3u8.py

      - name: Run France 5 Backup update script
        run: python3 ./scripts/france5-bck_m3u8.py
        
      - name: Run CSTAR M3U8 update script
        run: python3 ./scripts/cstar_m3u8.py
        
      - name: Run TFX M3U8 update script
        run: python3 ./scripts/tfx_m3u8.py
        
      - name: Run CHERIE25 M3U8 update script
        run: python3 ./scripts/cherie25_m3u8.py
        
      - name: Run ARTE M3U8 update script
        run: python3 ./scripts/arte_m3u8.py

      - name: Run ARTE Backup M3U8 update script
        run: python3 ./scripts/arte-bck_m3u8.py

      - name: Run TF1 Séries Films M3U8 update script
        run: python3 ./scripts/tf1-series-films_m3u8.py

      - name: Run France TV Séries M3U8 update script
        run: python3 ./scripts/france-tv-series_m3u8.py

      - name: Run France TV Docs M3U8 update script
        run: python3 ./scripts/france-tv-docs_m3u8.py
        
      - name: Run T18 M3U8 update script
        run: python3 ./scripts/t18_m3u8.py
        
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        run: |
          git add Streams/
          git diff --cached --quiet || git commit -m "Auto Sync M3U8 files: $(date)"

      - name: Push changes
        env:
          TOKEN: ${{ secrets.PAT_TOKEN }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          git push https://x-access-token:${TOKEN}@github.com/${REPO}.git HEAD:${BRANCH}
